[package]
name = "watim"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.23"
itertools = "0.10.3"
thiserror = "1.0.31"
env_logger = "0.9.0"
log = "0.4.17"
tempfile = "3.3.0"

[dev-dependencies]
