on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Bootstrap
      run: python ./bootstrap.py ./v2/main.watim > watim.wat && wat2wasm watim.wasm
    - name: Run tests
      run: ./test.py

