on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install mypy
      run: pip install mypy
    - name: Run mypy
      run: mypy ./bootstrap.py
    - name: Bootstrap
      run: python ./bootstrap.py ./v2/main.watim > watim.wat && wat2wasm watim.wasm
    - name: Run tests
      run: ./test.py

