on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install mypy and ruff
      run: pip install mypy ruff
    - name: Run mypy
      run: mypy bootstrap
    - name: Run ruff
      run: ruff check
    - name: Install wabt and wasmtime
      run: |
        sudo apt-get install wabt
        curl https://wasmtime.dev/install.sh -sSf | bash
    - name: Add wasmtime to PATH
      run: echo "PATH=$HOME/.wasmtime/bin:$PATH" >> $GITHUB_ENV
    - name: Bootstrap
      run: |
        bash ./bootstrap-native.sh
    - name: Run tests on bootstrap compiler
      run: |
        ./test.py
    - name: Run tests on native compiler
      run: |
        ./test.py --native
    - name: Run standard library tests
      run: |
        ls ./std-tests/*.watim -1 | xargs -L1 ./run.sh

